/* tslint:disable */
/* eslint-disable */
/**
 * Cats example
 * The cats API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { GetPage200Response } from '../models'
import { GetPage200ResponseFromJSON, GetPage200ResponseToJSON } from '../models'

export interface GetPageRequest {
  current?: number
  pageSize?: number
}

/**
 *
 */
export class HomeApi extends runtime.BaseAPI {
  /**
   * 获取分页信息
   */
  async getPageRaw(
    requestParameters: GetPageRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<GetPage200Response>> {
    const queryParameters: any = {}

    if (requestParameters.current !== undefined) {
      queryParameters['current'] = requestParameters.current
    }

    if (requestParameters.pageSize !== undefined) {
      queryParameters['pageSize'] = requestParameters.pageSize
    }

    const headerParameters: runtime.HTTPHeaders = {}

    const response = await this.request(
      {
        path: `/page`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GetPage200ResponseFromJSON(jsonValue),
    )
  }

  /**
   * 获取分页信息
   */
  async getPage(
    requestParameters: GetPageRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<GetPage200Response> {
    const response = await this.getPageRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
