import eslintPluginUnicorn from 'eslint-plugin-unicorn'
import { defineConfig } from 'oxlint'

export default defineConfig({
  plugins: ['typescript', 'unicorn', 'react', 'import', 'react-perf', 'oxc', 'promise'],
  categories: {
    correctness: 'error',
  },
  env: {
    builtin: true,
    es2025: true,
  },
  ignorePatterns: ['dist/', 'src/api/', 'src/routeTree.gen.ts', 'schema.d.ts'],
  rules: {
    ...eslintPluginUnicorn.configs.recommended.rules,
    'no-case-declarations': 'error',
    'no-empty': 'error',
    'no-fallthrough': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-unexpected-multiline': 'error',
    '@typescript-eslint/ban-ts-comment': ['error', { minimumDescriptionLength: 10 }],
    'no-array-constructor': 'error',
    '@typescript-eslint/no-dynamic-delete': 'error',
    '@typescript-eslint/no-empty-object-type': 'error',
    '@typescript-eslint/no-explicit-any': 'error',
    '@typescript-eslint/no-extraneous-class': 'error',
    '@typescript-eslint/no-namespace': 'error',
    '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'error',
    '@typescript-eslint/no-non-null-assertion': 'error',
    '@typescript-eslint/no-require-imports': 'error',
    '@typescript-eslint/no-unnecessary-type-constraint': 'error',
    '@typescript-eslint/no-unsafe-function-type': 'error',
    'no-useless-constructor': 'error',
    'no-throw-literal': 'off',
    '@typescript-eslint/prefer-literal-enum-member': 'error',
    'prefer-promise-reject-errors': 'off',
    'require-await': 'off',
    '@typescript-eslint/adjacent-overload-signatures': 'error',
    '@typescript-eslint/array-type': 'error',
    '@typescript-eslint/ban-tslint-comment': 'error',
    '@typescript-eslint/consistent-generic-constructors': 'error',
    '@typescript-eslint/consistent-indexed-object-style': 'error',
    '@typescript-eslint/consistent-type-definitions': 'error',
    '@typescript-eslint/no-confusing-non-null-assertion': 'error',
    'no-empty-function': 'error',
    '@typescript-eslint/no-inferrable-types': 'error',
    '@typescript-eslint/prefer-for-of': 'error',
    '@typescript-eslint/prefer-function-type': 'error',
    'no-negated-condition': 'off',
    'no-nested-ternary': 'off',
    'react/no-array-index-key': 'error',
    'react/button-has-type': 'error',
    'react/no-danger': 'error',
    'react/jsx-no-comment-textnodes': 'error',
    'react/jsx-no-useless-fragment': 'error',
    'react/self-closing-comp': 'error',
    'react/jsx-boolean-value': 'error',
    'react/jsx-curly-brace-presence': 'error',
    'typescript/consistent-type-imports': 'error',
    'import/no-empty-named-blocks': 'error',
    'import/no-duplicates': 'error',
  },
})
