/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as NeedAuthRouteImport } from './routes/_need-auth/route'
import { Route as NeedAuthSplatImport } from './routes/_need-auth/$'

// Create Virtual Routes

const NeedAuthIndexLazyImport = createFileRoute('/_need-auth/')()
const NeedAuthTableIndexLazyImport = createFileRoute('/_need-auth/table/')()
const NeedAuthStateReactQueryLazyImport = createFileRoute(
  '/_need-auth/state/react-query',
)()
const NeedAuthFormFormilyLazyImport = createFileRoute(
  '/_need-auth/form/formily',
)()
const NeedAuthStateJotaiIndexLazyImport = createFileRoute(
  '/_need-auth/state/jotai/',
)()

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const NeedAuthRouteRoute = NeedAuthRouteImport.update({
  id: '/_need-auth',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_need-auth/route.lazy').then((d) => d.Route),
)

const NeedAuthIndexLazyRoute = NeedAuthIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NeedAuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_need-auth/index.lazy').then((d) => d.Route),
)

const NeedAuthSplatRoute = NeedAuthSplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => NeedAuthRouteRoute,
} as any)

const NeedAuthTableIndexLazyRoute = NeedAuthTableIndexLazyImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => NeedAuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_need-auth/table/index.lazy').then((d) => d.Route),
)

const NeedAuthStateReactQueryLazyRoute =
  NeedAuthStateReactQueryLazyImport.update({
    id: '/state/react-query',
    path: '/state/react-query',
    getParentRoute: () => NeedAuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_need-auth/state/react-query.lazy').then((d) => d.Route),
  )

const NeedAuthFormFormilyLazyRoute = NeedAuthFormFormilyLazyImport.update({
  id: '/form/formily',
  path: '/form/formily',
  getParentRoute: () => NeedAuthRouteRoute,
} as any).lazy(() =>
  import('./routes/_need-auth/form/formily.lazy').then((d) => d.Route),
)

const NeedAuthStateJotaiIndexLazyRoute =
  NeedAuthStateJotaiIndexLazyImport.update({
    id: '/state/jotai/',
    path: '/state/jotai/',
    getParentRoute: () => NeedAuthRouteRoute,
  } as any).lazy(() =>
    import('./routes/_need-auth/state/jotai/index.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_need-auth': {
      id: '/_need-auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NeedAuthRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_need-auth/$': {
      id: '/_need-auth/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof NeedAuthSplatImport
      parentRoute: typeof NeedAuthRouteImport
    }
    '/_need-auth/': {
      id: '/_need-auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof NeedAuthIndexLazyImport
      parentRoute: typeof NeedAuthRouteImport
    }
    '/_need-auth/form/formily': {
      id: '/_need-auth/form/formily'
      path: '/form/formily'
      fullPath: '/form/formily'
      preLoaderRoute: typeof NeedAuthFormFormilyLazyImport
      parentRoute: typeof NeedAuthRouteImport
    }
    '/_need-auth/state/react-query': {
      id: '/_need-auth/state/react-query'
      path: '/state/react-query'
      fullPath: '/state/react-query'
      preLoaderRoute: typeof NeedAuthStateReactQueryLazyImport
      parentRoute: typeof NeedAuthRouteImport
    }
    '/_need-auth/table/': {
      id: '/_need-auth/table/'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof NeedAuthTableIndexLazyImport
      parentRoute: typeof NeedAuthRouteImport
    }
    '/_need-auth/state/jotai/': {
      id: '/_need-auth/state/jotai/'
      path: '/state/jotai'
      fullPath: '/state/jotai'
      preLoaderRoute: typeof NeedAuthStateJotaiIndexLazyImport
      parentRoute: typeof NeedAuthRouteImport
    }
  }
}

// Create and export the route tree

interface NeedAuthRouteRouteChildren {
  NeedAuthSplatRoute: typeof NeedAuthSplatRoute
  NeedAuthIndexLazyRoute: typeof NeedAuthIndexLazyRoute
  NeedAuthFormFormilyLazyRoute: typeof NeedAuthFormFormilyLazyRoute
  NeedAuthStateReactQueryLazyRoute: typeof NeedAuthStateReactQueryLazyRoute
  NeedAuthTableIndexLazyRoute: typeof NeedAuthTableIndexLazyRoute
  NeedAuthStateJotaiIndexLazyRoute: typeof NeedAuthStateJotaiIndexLazyRoute
}

const NeedAuthRouteRouteChildren: NeedAuthRouteRouteChildren = {
  NeedAuthSplatRoute: NeedAuthSplatRoute,
  NeedAuthIndexLazyRoute: NeedAuthIndexLazyRoute,
  NeedAuthFormFormilyLazyRoute: NeedAuthFormFormilyLazyRoute,
  NeedAuthStateReactQueryLazyRoute: NeedAuthStateReactQueryLazyRoute,
  NeedAuthTableIndexLazyRoute: NeedAuthTableIndexLazyRoute,
  NeedAuthStateJotaiIndexLazyRoute: NeedAuthStateJotaiIndexLazyRoute,
}

const NeedAuthRouteRouteWithChildren = NeedAuthRouteRoute._addFileChildren(
  NeedAuthRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof NeedAuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/$': typeof NeedAuthSplatRoute
  '/': typeof NeedAuthIndexLazyRoute
  '/form/formily': typeof NeedAuthFormFormilyLazyRoute
  '/state/react-query': typeof NeedAuthStateReactQueryLazyRoute
  '/table': typeof NeedAuthTableIndexLazyRoute
  '/state/jotai': typeof NeedAuthStateJotaiIndexLazyRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof NeedAuthSplatRoute
  '/': typeof NeedAuthIndexLazyRoute
  '/form/formily': typeof NeedAuthFormFormilyLazyRoute
  '/state/react-query': typeof NeedAuthStateReactQueryLazyRoute
  '/table': typeof NeedAuthTableIndexLazyRoute
  '/state/jotai': typeof NeedAuthStateJotaiIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_need-auth': typeof NeedAuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_need-auth/$': typeof NeedAuthSplatRoute
  '/_need-auth/': typeof NeedAuthIndexLazyRoute
  '/_need-auth/form/formily': typeof NeedAuthFormFormilyLazyRoute
  '/_need-auth/state/react-query': typeof NeedAuthStateReactQueryLazyRoute
  '/_need-auth/table/': typeof NeedAuthTableIndexLazyRoute
  '/_need-auth/state/jotai/': typeof NeedAuthStateJotaiIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/$'
    | '/'
    | '/form/formily'
    | '/state/react-query'
    | '/table'
    | '/state/jotai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/$'
    | '/'
    | '/form/formily'
    | '/state/react-query'
    | '/table'
    | '/state/jotai'
  id:
    | '__root__'
    | '/_need-auth'
    | '/login'
    | '/_need-auth/$'
    | '/_need-auth/'
    | '/_need-auth/form/formily'
    | '/_need-auth/state/react-query'
    | '/_need-auth/table/'
    | '/_need-auth/state/jotai/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  NeedAuthRouteRoute: typeof NeedAuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  NeedAuthRouteRoute: NeedAuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_need-auth",
        "/login"
      ]
    },
    "/_need-auth": {
      "filePath": "_need-auth/route.tsx",
      "children": [
        "/_need-auth/$",
        "/_need-auth/",
        "/_need-auth/form/formily",
        "/_need-auth/state/react-query",
        "/_need-auth/table/",
        "/_need-auth/state/jotai/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_need-auth/$": {
      "filePath": "_need-auth/$.tsx",
      "parent": "/_need-auth"
    },
    "/_need-auth/": {
      "filePath": "_need-auth/index.lazy.tsx",
      "parent": "/_need-auth"
    },
    "/_need-auth/form/formily": {
      "filePath": "_need-auth/form/formily.lazy.tsx",
      "parent": "/_need-auth"
    },
    "/_need-auth/state/react-query": {
      "filePath": "_need-auth/state/react-query.lazy.tsx",
      "parent": "/_need-auth"
    },
    "/_need-auth/table/": {
      "filePath": "_need-auth/table/index.lazy.tsx",
      "parent": "/_need-auth"
    },
    "/_need-auth/state/jotai/": {
      "filePath": "_need-auth/state/jotai/index.lazy.tsx",
      "parent": "/_need-auth"
    }
  }
}
ROUTE_MANIFEST_END */
