/* tslint:disable */
/* eslint-disable */
/**
 * JSON Placeholder
 * Fake Online REST API for Testing and Prototyping
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Comment
 */
export interface Comment {
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof Comment
     */
    postId?: number;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof Comment
     */
    body?: string;
}

/**
 * Check if a given object implements the Comment interface.
 */
export function instanceOfComment(value: object): boolean {
    return true;
}

export function CommentFromJSON(json: any): Comment {
    return CommentFromJSONTyped(json, false);
}

export function CommentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Comment {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'postId': json['postId'] == null ? undefined : json['postId'],
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'body': json['body'] == null ? undefined : json['body'],
    };
}

export function CommentToJSON(value?: Comment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'postId': value['postId'],
        'name': value['name'],
        'email': value['email'],
        'body': value['body'],
    };
}

