/* tslint:disable */
/* eslint-disable */
/**
 * Cats example
 * The cats API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface Page
 */
export interface Page {
  /**
   *
   * @type {number}
   * @memberof Page
   */
  current: number
  /**
   *
   * @type {number}
   * @memberof Page
   */
  pageSize: number
  /**
   *
   * @type {number}
   * @memberof Page
   */
  total: number
  /**
   *
   * @type {Array<string>}
   * @memberof Page
   */
  data: Array<string>
}

/**
 * Check if a given object implements the Page interface.
 */
export function instanceOfPage(value: object): boolean {
  let isInstance = true
  isInstance = isInstance && 'current' in value
  isInstance = isInstance && 'pageSize' in value
  isInstance = isInstance && 'total' in value
  isInstance = isInstance && 'data' in value

  return isInstance
}

export function PageFromJSON(json: any): Page {
  return PageFromJSONTyped(json, false)
}

export function PageFromJSONTyped(json: any, ignoreDiscriminator: boolean): Page {
  if (json === undefined || json === null) {
    return json
  }
  return {
    current: json['current'],
    pageSize: json['pageSize'],
    total: json['total'],
    data: json['data'],
  }
}

export function PageToJSON(value?: Page | null): any {
  if (value === undefined) {
    return undefined
  }
  if (value === null) {
    return null
  }
  return {
    current: value.current,
    pageSize: value.pageSize,
    total: value.total,
    data: value.data,
  }
}
