/* tslint:disable */
/* eslint-disable */
/**
 * Cats example
 * The cats API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PageItem
 */
export interface PageItem {
  /**
   *
   * @type {number}
   * @memberof PageItem
   */
  id: number;
  /**
   *
   * @type {string}
   * @memberof PageItem
   */
  title: string;
  /**
   *
   * @type {string}
   * @memberof PageItem
   */
  descript: string;
  /**
   *
   * @type {string}
   * @memberof PageItem
   */
  image: string;
  /**
   *
   * @type {number}
   * @memberof PageItem
   */
  status: PageItemStatusEnum;
  /**
   *
   * @type {number}
   * @memberof PageItem
   */
  price: number;
}

/**
 * @export
 */
export const PageItemStatusEnum = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
  NUMBER_5: 5,
} as const;
export type PageItemStatusEnum =
  (typeof PageItemStatusEnum)[keyof typeof PageItemStatusEnum];

/**
 * Check if a given object implements the PageItem interface.
 */
export function instanceOfPageItem(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'id' in value;
  isInstance = isInstance && 'title' in value;
  isInstance = isInstance && 'descript' in value;
  isInstance = isInstance && 'image' in value;
  isInstance = isInstance && 'status' in value;
  isInstance = isInstance && 'price' in value;

  return isInstance;
}

export function PageItemFromJSON(json: any): PageItem {
  return PageItemFromJSONTyped(json, false);
}

export function PageItemFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PageItem {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json['id'],
    title: json['title'],
    descript: json['descript'],
    image: json['image'],
    status: json['status'],
    price: json['price'],
  };
}

export function PageItemToJSON(value?: PageItem | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    title: value.title,
    descript: value.descript,
    image: value.image,
    status: value.status,
    price: value.price,
  };
}
