/* tslint:disable */
/* eslint-disable */
/**
 * JSON Placeholder
 * Fake Online REST API for Testing and Prototyping
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserAddressGeo
 */
export interface UserAddressGeo {
    /**
     * 
     * @type {string}
     * @memberof UserAddressGeo
     */
    lat?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddressGeo
     */
    lng?: string;
}

/**
 * Check if a given object implements the UserAddressGeo interface.
 */
export function instanceOfUserAddressGeo(value: object): value is UserAddressGeo {
    return true;
}

export function UserAddressGeoFromJSON(json: any): UserAddressGeo {
    return UserAddressGeoFromJSONTyped(json, false);
}

export function UserAddressGeoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAddressGeo {
    if (json == null) {
        return json;
    }
    return {
        
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lng': json['lng'] == null ? undefined : json['lng'],
    };
}

export function UserAddressGeoToJSON(json: any): UserAddressGeo {
    return UserAddressGeoToJSONTyped(json, false);
}

export function UserAddressGeoToJSONTyped(value?: UserAddressGeo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lat': value['lat'],
        'lng': value['lng'],
    };
}

