/* tslint:disable */
/* eslint-disable */
/**
 * JSON Placeholder
 * Fake Online REST API for Testing and Prototyping
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCompany
 */
export interface UserCompany {
    /**
     * 
     * @type {string}
     * @memberof UserCompany
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCompany
     */
    catchPhrase?: string;
    /**
     * 
     * @type {string}
     * @memberof UserCompany
     */
    bs?: string;
}

/**
 * Check if a given object implements the UserCompany interface.
 */
export function instanceOfUserCompany(value: object): boolean {
    return true;
}

export function UserCompanyFromJSON(json: any): UserCompany {
    return UserCompanyFromJSONTyped(json, false);
}

export function UserCompanyFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCompany {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'catchPhrase': json['catchPhrase'] == null ? undefined : json['catchPhrase'],
        'bs': json['bs'] == null ? undefined : json['bs'],
    };
}

export function UserCompanyToJSON(value?: UserCompany | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'catchPhrase': value['catchPhrase'],
        'bs': value['bs'],
    };
}

